In [1]:
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func, inspect
from flask import Flask, jsonify

In [2]:
#Database Setup

In [3]:
engine = create_engine("sqlite:///data/BOTULISM.db")

In [4]:
inspector = inspect(engine)
for table in inspector.get_table_names():
    print(table)
    columns = inspector.get_columns(table)
    for column in columns:
        print('     ', column['name'])

BOTULISM
      BotId
      state_name
      record_year
      BotType
      ToxinType
      record_count
sqlite_sequence
      name
      seq

In [5]:
Base = automap_base()
Base.prepare(engine, reflect=True)

In [6]:
session = Session(engine)

In [7]:
Base.classes.keys()

['BOTULISM']

In [8]:
bot_data = Base.classes.BOTULISM

In [11]:
#Retrieving all records
all_results = session.query(bot_data.state_name, 
                        bot_data.record_year, 
                        bot_data.BotType,
                        bot_data.ToxinType,
                        bot_data.record_count,
                        bot_data.BotId).all()

In [12]:
all_records = []

for state, year, botType, toxType, count, botID in all_results:
    results_dict = {}
    results_dict["state"] = state
    results_dict["year"] = year
    results_dict["botType"] = botType
    results_dict["toxType"] = toxType
    results_dict["count"] = count
    results_dict["botID"] = botID
    all_records.append(results_dict)

In [13]:
#Creating list of unique states

all_states = session.query(bot_data.state_name).distinct().all()

state_names = []

for i in all_states:
    for state in i:
        #create dict here if necessary to work in app
        state_names.append(state)

In [14]:
#Creating list of unique Botulism types (BotType)

all_botTypes = session.query(bot_data.BotType).distinct().all()

bot_types = []

for i in all_botTypes:
    for kind in i:
        #create dict here if necessary to work in app
        bot_types.append(kind)

In [15]:
#Creating list of unique Toxin types (ToxinType)

all_toxTypes = session.query(bot_data.ToxinType).distinct().all()

tox_types = []

for i in all_toxTypes:
    for kind in i:
        #create dict here if necessary to work in app
        tox_types.append(kind)

In [16]:
#Creating list of unique years (record_year)

all_years = session.query(bot_data.record_year).order_by(bot_data.record_year).distinct().all()

years = []

for i in all_years:
    for year in i:
        #create dict here if necessary to work in app
        years.append(year)

In [17]:
#Filtering selection by states

state_data = session.query(bot_data.state_name, 
                        bot_data.record_year, 
                        bot_data.BotType,
                        bot_data.ToxinType,
                        bot_data.record_count).filter(bot_data.state_name == "California").all()

In [18]:
#Creating lists for json formatting
years = []

foodborne_bot = []
infant_bot = []
wound_bot = []
other_bot = []

unknown_tox = []
E_tox =[]
B_tox =[]
A_tox =[]
F_tox =[]
AB_tox =[]
Ba_tox =[]
Bf_tox =[]
EF_tox =[]
ABE_tox =[]
Ab_tox =[]
BF_tox =[]

In [19]:
#Appending data to lists
for i in state_data:
    years.append(i[1])

In [20]:
#Appending data to lists
for i in state_data:
    if i[2] == "Foodborne":
        foodborne_bot.append(i[4])
    else:
        foodborne_bot.append('0')
        
for i in state_data:
    if i[2] == "Infant":
        infant_bot.append(i[4])
    else:
        infant_bot.append('0')
        
for i in state_data:
    if i[2] == "Wound":
        wound_bot.append(i[4])
    else:
        wound_bot.append('0')
        
for i in state_data:
    if i[2] == "Other":
        other_bot.append(i[4])
    else:
        other_bot.append('0')

In [21]:
#Appending data to lists
for i in state_data:
    if i[3] == "Unknown":
        unknown_tox.append(i[4])
    else:
        unknown_tox.append('0')
        
for i in state_data:
    if i[3] == "E":
        E_tox.append(i[4])
    else:
        E_tox.append('0')
        
for i in state_data:
    if i[3] == "B":
        B_tox.append(i[4])
    else:
        B_tox.append('0')
        
for i in state_data:
    if i[3] == "A":
        A_tox.append(i[4])
    else:
        A_tox.append('0')
        
for i in state_data:
    if i[3] == "F":
        F_tox.append(i[4])
    else:
        F_tox.append('0')
        
for i in state_data:
    if i[3] == "AB":
        AB_tox.append(i[4])
    else:
        AB_tox.append('0')
        
for i in state_data:
    if i[3] == "Ba":
        Ba_tox.append(i[4])
    else:
        Ba_tox.append('0')
        
for i in state_data:
    if i[3] == "Bf":
        Bf_tox.append(i[4])
    else:
        Bf_tox.append('0')
        
for i in state_data:
    if i[3] == "EF":
        EF_tox.append(i[4])
    else:
        EF_tox.append('0')
        
for i in state_data:
    if i[3] == "ABE":
        ABE_tox.append(i[4])
    else:
        ABE_tox.append('0')
        
for i in state_data:
    if i[3] == "Ab":
        Ab_tox.append(i[4])
    else:
        Ab_tox.append('0')
        
for i in state_data:
    if i[3] == "BF":
        BF_tox.append(i[4])
    else:
        BF_tox.append('0')

In [48]:
foodborne_data_teset = session.query(bot_data.state_name,
                               bot_data.BotType,
                        bot_data.record_year,
                       bot_data.record_count).\
                        filter(bot_data.state_name == "Alaska").\
                        filter(bot_data.BotType == "Foodborne").all()

In [49]:
foodborne_data_teset

[('Alaska', 'Foodborne', '1947', '3'),
 ('Alaska', 'Foodborne', '1948', '4'),
 ('Alaska', 'Foodborne', '1950', '5'),
 ('Alaska', 'Foodborne', '1952', '1'),
 ('Alaska', 'Foodborne', '1956', '5'),
 ('Alaska', 'Foodborne', '1959', '10'),
 ('Alaska', 'Foodborne', '1960', '2'),
 ('Alaska', 'Foodborne', '1967', '1'),
 ('Alaska', 'Foodborne', '1968', '1'),
 ('Alaska', 'Foodborne', '1970', '1'),
 ('Alaska', 'Foodborne', '1971', '2'),
 ('Alaska', 'Foodborne', '1973', '9'),
 ('Alaska', 'Foodborne', '1973', '3'),
 ('Alaska', 'Foodborne', '1974', '1'),
 ('Alaska', 'Foodborne', '1974', '2'),
 ('Alaska', 'Foodborne', '1974', '3'),
 ('Alaska', 'Foodborne', '1974', '1'),
 ('Alaska', 'Foodborne', '1975', '3'),
 ('Alaska', 'Foodborne', '1976', '3'),
 ('Alaska', 'Foodborne', '1976', '2'),
 ('Alaska', 'Foodborne', '1976', '9'),
 ('Alaska', 'Foodborne', '1977', '2'),
 ('Alaska', 'Foodborne', '1977', '2'),
 ('Alaska', 'Foodborne', '1977', '7'),
 ('Alaska', 'Foodborne', '1979', '3'),
 ('Alaska', 'Foodborne', '1980', '2'),
 ('Alaska', 'Foodborne', '1981', '9'),
 ('Alaska', 'Foodborne', '1982', '3'),
 ('Alaska', 'Foodborne', '1983', '1'),
 ('Alaska', 'Foodborne', '1983', '1'),
 ('Alaska', 'Foodborne', '1984', '1'),
 ('Alaska', 'Foodborne', '1984', '4'),
 ('Alaska', 'Foodborne', '1984', '1'),
 ('Alaska', 'Foodborne', '1985', '4'),
 ('Alaska', 'Foodborne', '1985', '14'),
 ('Alaska', 'Foodborne', '1986', '8'),
 ('Alaska', 'Foodborne', '1987', '1'),
 ('Alaska', 'Foodborne', '1988', '2'),
 ('Alaska', 'Foodborne', '1988', '30'),
 ('Alaska', 'Foodborne', '1989', '5'),
 ('Alaska', 'Foodborne', '1990', '8'),
 ('Alaska', 'Foodborne', '1991', '20'),
 ('Alaska', 'Foodborne', '1992', '1'),
 ('Alaska', 'Foodborne', '1992', '7'),
 ('Alaska', 'Foodborne', '1993', '1'),
 ('Alaska', 'Foodborne', '1993', '1'),
 ('Alaska', 'Foodborne', '1993', '2'),
 ('Alaska', 'Foodborne', '1994', '2'),
 ('Alaska', 'Foodborne', '1994', '9'),
 ('Alaska', 'Foodborne', '1995', '2'),
 ('Alaska', 'Foodborne', '1995', '2'),
 ('Alaska', 'Foodborne', '1996', '1'),
 ('Alaska', 'Foodborne', '1996', '8'),
 ('Alaska', 'Foodborne', '1996', '1'),
 ('Alaska', 'Foodborne', '1997', '1'),
 ('Alaska', 'Foodborne', '1997', '14'),
 ('Alaska', 'Foodborne', '1998', '9'),
 ('Alaska', 'Foodborne', '1999', '12'),
 ('Alaska', 'Foodborne', '2001', '1'),
 ('Alaska', 'Foodborne', '2001', '8'),
 ('Alaska', 'Foodborne', '2002', '14'),
 ('Alaska', 'Foodborne', '2003', '2'),
 ('Alaska', 'Foodborne', '2004', '1'),
 ('Alaska', 'Foodborne', '2005', '8'),
 ('Alaska', 'Foodborne', '2006', '1'),
 ('Alaska', 'Foodborne', '2006', '5'),
 ('Alaska', 'Foodborne', '2007', '3'),
 ('Alaska', 'Foodborne', '2007', '7'),
 ('Alaska', 'Foodborne', '2008', '6'),
 ('Alaska', 'Foodborne', '2008', '2'),
 ('Alaska', 'Foodborne', '2010', '2'),
 ('Alaska', 'Foodborne', '2010', '2'),
 ('Alaska', 'Foodborne', '2010', '1'),
 ('Alaska', 'Foodborne', '2011', '5'),
 ('Alaska', 'Foodborne', '2012', '3'),
 ('Alaska', 'Foodborne', '2013', '1'),
 ('Alaska', 'Foodborne', '2014', '7'),
 ('Alaska', 'Foodborne', '2015', '5'),
 ('Alaska', 'Foodborne', '2016', '2'),
 ('Alaska', 'Foodborne', '2017', '4')]

In [50]:
foodborne_data = session.query(bot_data.state_name,
                               bot_data.BotType,
                        bot_data.record_year,
                       func.sum(bot_data.record_count)).\
                        filter(bot_data.BotType == "Foodborne").\
                        filter(bot_data.state_name == "Alaska").\
                        group_by(bot_data.record_year).\
                        order_by(bot_data.state_name).all()

In [51]:
foodborne_data

[('Alaska', 'Foodborne', '1947', 3),
 ('Alaska', 'Foodborne', '1948', 4),
 ('Alaska', 'Foodborne', '1950', 5),
 ('Alaska', 'Foodborne', '1952', 1),
 ('Alaska', 'Foodborne', '1956', 5),
 ('Alaska', 'Foodborne', '1959', 10),
 ('Alaska', 'Foodborne', '1960', 2),
 ('Alaska', 'Foodborne', '1967', 1),
 ('Alaska', 'Foodborne', '1968', 1),
 ('Alaska', 'Foodborne', '1970', 1),
 ('Alaska', 'Foodborne', '1971', 2),
 ('Alaska', 'Foodborne', '1973', 12),
 ('Alaska', 'Foodborne', '1974', 7),
 ('Alaska', 'Foodborne', '1975', 3),
 ('Alaska', 'Foodborne', '1976', 14),
 ('Alaska', 'Foodborne', '1977', 11),
 ('Alaska', 'Foodborne', '1979', 3),
 ('Alaska', 'Foodborne', '1980', 2),
 ('Alaska', 'Foodborne', '1981', 9),
 ('Alaska', 'Foodborne', '1982', 3),
 ('Alaska', 'Foodborne', '1983', 2),
 ('Alaska', 'Foodborne', '1984', 6),
 ('Alaska', 'Foodborne', '1985', 18),
 ('Alaska', 'Foodborne', '1986', 8),
 ('Alaska', 'Foodborne', '1987', 1),
 ('Alaska', 'Foodborne', '1988', 32),
 ('Alaska', 'Foodborne', '1989', 5),
 ('Alaska', 'Foodborne', '1990', 8),
 ('Alaska', 'Foodborne', '1991', 20),
 ('Alaska', 'Foodborne', '1992', 8),
 ('Alaska', 'Foodborne', '1993', 4),
 ('Alaska', 'Foodborne', '1994', 11),
 ('Alaska', 'Foodborne', '1995', 4),
 ('Alaska', 'Foodborne', '1996', 10),
 ('Alaska', 'Foodborne', '1997', 15),
 ('Alaska', 'Foodborne', '1998', 9),
 ('Alaska', 'Foodborne', '1999', 12),
 ('Alaska', 'Foodborne', '2001', 9),
 ('Alaska', 'Foodborne', '2002', 14),
 ('Alaska', 'Foodborne', '2003', 2),
 ('Alaska', 'Foodborne', '2004', 1),
 ('Alaska', 'Foodborne', '2005', 8),
 ('Alaska', 'Foodborne', '2006', 6),
 ('Alaska', 'Foodborne', '2007', 10),
 ('Alaska', 'Foodborne', '2008', 8),
 ('Alaska', 'Foodborne', '2010', 5),
 ('Alaska', 'Foodborne', '2011', 5),
 ('Alaska', 'Foodborne', '2012', 3),
 ('Alaska', 'Foodborne', '2013', 1),
 ('Alaska', 'Foodborne', '2014', 7),
 ('Alaska', 'Foodborne', '2015', 5),
 ('Alaska', 'Foodborne', '2016', 2),
 ('Alaska', 'Foodborne', '2017', 4)]

In [67]:
all_states = session.query(bot_data.state_name).distinct().all()

state_names = []

for i in all_states:
    for state in i:
        #create dict here if necessary to work in app
        state_names.append(state)

In [86]:

food_children = []
for state in state_names:
    
    
    foodborne_data = session.query(bot_data.state_name,
                               bot_data.BotType,
                        bot_data.record_year,
                       func.sum(bot_data.record_count)).\
                        filter(bot_data.BotType == "Foodborne").\
                        filter(bot_data.state_name == state).\
                        group_by(bot_data.record_year).\
                        order_by(bot_data.state_name).all()
    
    children = []
    
    for i in foodborne_data:

        children.append({"name": i[2], "value": i[3]})
        
    
        
    one_state = {"name": state, "children": children}  
    food_children.append(one_state)

In [87]:
food_children

[{'name': 'Alaska',
  'children': [{'name': '1947', 'value': 3},
   {'name': '1948', 'value': 4},
   {'name': '1950', 'value': 5},
   {'name': '1952', 'value': 1},
   {'name': '1956', 'value': 5},
   {'name': '1959', 'value': 10},
   {'name': '1960', 'value': 2},
   {'name': '1967', 'value': 1},
   {'name': '1968', 'value': 1},
   {'name': '1970', 'value': 1},
   {'name': '1971', 'value': 2},
   {'name': '1973', 'value': 12},
   {'name': '1974', 'value': 7},
   {'name': '1975', 'value': 3},
   {'name': '1976', 'value': 14},
   {'name': '1977', 'value': 11},
   {'name': '1979', 'value': 3},
   {'name': '1980', 'value': 2},
   {'name': '1981', 'value': 9},
   {'name': '1982', 'value': 3},
   {'name': '1983', 'value': 2},
   {'name': '1984', 'value': 6},
   {'name': '1985', 'value': 18},
   {'name': '1986', 'value': 8},
   {'name': '1987', 'value': 1},
   {'name': '1988', 'value': 32},
   {'name': '1989', 'value': 5},
   {'name': '1990', 'value': 8},
   {'name': '1991', 'value': 20},
   {'name': '1992', 'value': 8},
   {'name': '1993', 'value': 4},
   {'name': '1994', 'value': 11},
   {'name': '1995', 'value': 4},
   {'name': '1996', 'value': 10},
   {'name': '1997', 'value': 15},
   {'name': '1998', 'value': 9},
   {'name': '1999', 'value': 12},
   {'name': '2001', 'value': 9},
   {'name': '2002', 'value': 14},
   {'name': '2003', 'value': 2},
   {'name': '2004', 'value': 1},
   {'name': '2005', 'value': 8},
   {'name': '2006', 'value': 6},
   {'name': '2007', 'value': 10},
   {'name': '2008', 'value': 8},
   {'name': '2010', 'value': 5},
   {'name': '2011', 'value': 5},
   {'name': '2012', 'value': 3},
   {'name': '2013', 'value': 1},
   {'name': '2014', 'value': 7},
   {'name': '2015', 'value': 5},
   {'name': '2016', 'value': 2},
   {'name': '2017', 'value': 4}]},
 {'name': 'Alabama',
  'children': [{'name': '1928', 'value': 3},
   {'name': '1942', 'value': 1},
   {'name': '1962', 'value': 1},
   {'name': '1963', 'value': 3},
   {'name': '1964', 'value': 1},
   {'name': '1965', 'value': 2},
   {'name': '1974', 'value': 1}]},
 {'name': 'Arkansas',
  'children': [{'name': '1939', 'value': 2},
   {'name': '1961', 'value': 1},
   {'name': '1986', 'value': 3},
   {'name': '2000', 'value': 2},
   {'name': '2001', 'value': 1}]},
 {'name': 'Arizona',
  'children': [{'name': '1920', 'value': 5},
   {'name': '1945', 'value': 4},
   {'name': '1951', 'value': 1},
   {'name': '1955', 'value': 1},
   {'name': '1982', 'value': 3},
   {'name': '1983', 'value': 1},
   {'name': '1995', 'value': 1},
   {'name': '2001', 'value': 1},
   {'name': '2008', 'value': 1},
   {'name': '2011', 'value': 1},
   {'name': '2012', 'value': 12},
   {'name': '2014', 'value': 1}]},
 {'name': 'California',
  'children': [{'name': '1899', 'value': 1},
   {'name': '1902', 'value': 7},
   {'name': '1906', 'value': 3},
   {'name': '1910', 'value': 16},
   {'name': '1911', 'value': 1},
   {'name': '1912', 'value': 16},
   {'name': '1913', 'value': 16},
   {'name': '1914', 'value': 2},
   {'name': '1915', 'value': 8},
   {'name': '1916', 'value': 3},
   {'name': '1917', 'value': 10},
   {'name': '1918', 'value': 19},
   {'name': '1919', 'value': 14},
   {'name': '1920', 'value': 15},
   {'name': '1921', 'value': 3},
   {'name': '1922', 'value': 17},
   {'name': '1923', 'value': 10},
   {'name': '1924', 'value': 20},
   {'name': '1925', 'value': 8},
   {'name': '1926', 'value': 1},
   {'name': '1927', 'value': 4},
   {'name': '1928', 'value': 6},
   {'name': '1929', 'value': 10},
   {'name': '1930', 'value': 6},
   {'name': '1931', 'value': 12},
   {'name': '1932', 'value': 8},
   {'name': '1933', 'value': 10},
   {'name': '1934', 'value': 1},
   {'name': '1935', 'value': 21},
   {'name': '1936', 'value': 7},
   {'name': '1937', 'value': 13},
   {'name': '1938', 'value': 15},
   {'name': '1939', 'value': 14},
   {'name': '1940', 'value': 12},
   {'name': '1941', 'value': 17},
   {'name': '1942', 'value': 16},
   {'name': '1943', 'value': 11},
   {'name': '1944', 'value': 11},
   {'name': '1945', 'value': 22},
   {'name': '1946', 'value': 5},
   {'name': '1947', 'value': 6},
   {'name': '1948', 'value': 6},
   {'name': '1949', 'value': 2},
   {'name': '1950', 'value': 7},
   {'name': '1951', 'value': 12},
   {'name': '1952', 'value': 10},
   {'name': '1953', 'value': 2},
   {'name': '1954', 'value': 6},
   {'name': '1955', 'value': 3},
   {'name': '1956', 'value': 7},
   {'name': '1957', 'value': 5},
   {'name': '1958', 'value': 1},
   {'name': '1959', 'value': 3},
   {'name': '1962', 'value': 2},
   {'name': '1963', 'value': 10},
   {'name': '1964', 'value': 7},
   {'name': '1965', 'value': 2},
   {'name': '1966', 'value': 5},
   {'name': '1968', 'value': 4},
   {'name': '1969', 'value': 2},
   {'name': '1970', 'value': 2},
   {'name': '1971', 'value': 11},
   {'name': '1972', 'value': 18},
   {'name': '1973', 'value': 4},
   {'name': '1974', 'value': 3},
   {'name': '1975', 'value': 6},
   {'name': '1976', 'value': 8},
   {'name': '1977', 'value': 5},
   {'name': '1978', 'value': 3},
   {'name': '1979', 'value': 1},
   {'name': '1980', 'value': 4},
   {'name': '1981', 'value': 7},
   {'name': '1982', 'value': 11},
   {'name': '1983', 'value': 1},
   {'name': '1984', 'value': 7},
   {'name': '1985', 'value': 2},
   {'name': '1986', 'value': 6},
   {'name': '1987', 'value': 4},
   {'name': '1988', 'value': 1},
   {'name': '1989', 'value': 1},
   {'name': '1990', 'value': 3},
   {'name': '1991', 'value': 1},
   {'name': '1992', 'value': 2},
   {'name': '1993', 'value': 3},
   {'name': '1994', 'value': 6},
   {'name': '1995', 'value': 3},
   {'name': '1996', 'value': 3},
   {'name': '1997', 'value': 3},
   {'name': '1998', 'value': 6},
   {'name': '1999', 'value': 4},
   {'name': '2000', 'value': 3},
   {'name': '2001', 'value': 4},
   {'name': '2003', 'value': 2},
   {'name': '2004', 'value': 6},
   {'name': '2005', 'value': 3},
   {'name': '2006', 'value': 6},
   {'name': '2007', 'value': 1},
   {'name': '2008', 'value': 3},
   {'name': '2009', 'value': 4},
   {'name': '2010', 'value': 1},
   {'name': '2011', 'value': 1},
   {'name': '2012', 'value': 1},
   {'name': '2016', 'value': 3},
   {'name': '2017', 'value': 15}]},
 {'name': 'Colorado',
  'children': [{'name': '1912', 'value': 7},
   {'name': '1913', 'value': 5},
   {'name': '1915', 'value': 5},
   {'name': '1921', 'value': 5},
   {'name': '1924', 'value': 7},
   {'name': '1925', 'value': 5},
   {'name': '1927', 'value': 3},
   {'name': '1929', 'value': 6},
   {'name': '1930', 'value': 7},
   {'name': '1931', 'value': 4},
   {'name': '1932', 'value': 3},
   {'name': '1933', 'value': 1},
   {'name': '1934', 'value': 3},
   {'name': '1935', 'value': 8},
   {'name': '1936', 'value': 1},
   {'name': '1937', 'value': 3},
   {'name': '1938', 'value': 1},
   {'name': '1940', 'value': 4},
   {'name': '1941', 'value': 1},
   {'name': '1942', 'value': 11},
   {'name': '1944', 'value': 1},
   {'name': '1947', 'value': 2},
   {'name': '1948', 'value': 5},
   {'name': '1950', 'value': 3},
   {'name': '1951', 'value': 1},
   {'name': '1952', 'value': 1},
   {'name': '1953', 'value': 6},
   {'name': '1954', 'value': 2},
   {'name': '1955', 'value': 5},
   {'name': '1956', 'value': 6},
   {'name': '1957', 'value': 1},
   {'name': '1959', 'value': 2},
   {'name': '1962', 'value': 3},
   {'name': '1963', 'value': 2},
   {'name': '1967', 'value': 1},
   {'name': '1969', 'value': 7},
   {'name': '1970', 'value': 1},
   {'name': '1972', 'value': 1},
   {'name': '1977', 'value': 1},
   {'name': '1978', 'value': 9},
   {'name': '1980', 'value': 1},
   {'name': '1981', 'value': 1},
   {'name': '1982', 'value': 1},
   {'name': '1983', 'value': 2},
   {'name': '1988', 'value': 1},
   {'name': '1992', 'value': 2},
   {'name': '1995', 'value': 1},
   {'name': '1996', 'value': 1},
   {'name': '2003', 'value': 1},
   {'name': '2010', 'value': 1},
   {'name': '2014', 'value': 1}]},
 {'name': 'Connecticut',
  'children': [{'name': '1933', 'value': 5},
   {'name': '1942', 'value': 2},
   {'name': '1947', 'value': 2},
   {'name': '1976', 'value': 1},
   {'name': '1998', 'value': 1}]},
 {'name': '',
  'children': [{'name': '1946', 'value': 3},
   {'name': '1978', 'value': 3},
   {'name': '1992', 'value': 1},
   {'name': '2011', 'value': 1},
   {'name': '2012', 'value': 1}]},
 {'name': 'Delaware', 'children': [{'name': '2012', 'value': 1}]},
 {'name': 'Florida',
  'children': [{'name': '1916', 'value': 7},
   {'name': '1961', 'value': 1},
   {'name': '1975', 'value': 1},
   {'name': '1987', 'value': 4},
   {'name': '1988', 'value': 1},
   {'name': '1999', 'value': 4},
   {'name': '2006', 'value': 1}]},
 {'name': 'Georgia',
  'children': [{'name': '1943', 'value': 1},
   {'name': '1964', 'value': 1},
   {'name': '1974', 'value': 2},
   {'name': '1977', 'value': 1},
   {'name': '1978', 'value': 1},
   {'name': '1993', 'value': 4},
   {'name': '2006', 'value': 3},
   {'name': '2011', 'value': 1}]},
 {'name': 'Hawaii',
  'children': [{'name': '1981', 'value': 1},
   {'name': '1987', 'value': 1},
   {'name': '1988', 'value': 1},
   {'name': '1990', 'value': 4}]},
 {'name': 'Iowa',
  'children': [{'name': '1919', 'value': 5},
   {'name': '1974', 'value': 2},
   {'name': '1999', 'value': 1}]},
 {'name': 'Idaho',
  'children': [{'name': '1918', 'value': 4},
   {'name': '1932', 'value': 3},
   {'name': '1935', 'value': 1},
   {'name': '1939', 'value': 2},
   {'name': '1959', 'value': 6},
   {'name': '1961', 'value': 3},
   {'name': '1965', 'value': 3},
   {'name': '1969', 'value': 2},
   {'name': '1973', 'value': 1},
   {'name': '1974', 'value': 1},
   {'name': '1977', 'value': 1},
   {'name': '1981', 'value': 1},
   {'name': '1995', 'value': 6},
   {'name': '1996', 'value': 1}]},
 {'name': 'Illinois',
  'children': [{'name': '1915', 'value': 4},
   {'name': '1925', 'value': 2},
   {'name': '1929', 'value': 2},
   {'name': '1941', 'value': 1},
   {'name': '1944', 'value': 1},
   {'name': '1953', 'value': 4},
   {'name': '1956', 'value': 1},
   {'name': '1959', 'value': 1},
   {'name': '1967', 'value': 3},
   {'name': '1969', 'value': 1},
   {'name': '1970', 'value': 4},
   {'name': '1975', 'value': 1},
   {'name': '1983', 'value': 29},
   {'name': '1985', 'value': 1},
   {'name': '1991', 'value': 1},
   {'name': '1994', 'value': 1},
   {'name': '1997', 'value': 1},
   {'name': '2006', 'value': 1},
   {'name': '2014', 'value': 1},
   {'name': '2015', 'value': 2}]},
 {'name': 'Indiana',
  'children': [{'name': '1918', 'value': 7},
   {'name': '1921', 'value': 2},
   {'name': '1922', 'value': 9},
   {'name': '1954', 'value': 2},
   {'name': '1966', 'value': 2},
   {'name': '1969', 'value': 1},
   {'name': '1999', 'value': 1},
   {'name': '2007', 'value': 3},
   {'name': '2008', 'value': 1}]},
 {'name': 'Kansas',
  'children': [{'name': '1964', 'value': 7},
   {'name': '1970', 'value': 1},
   {'name': '1995', 'value': 1}]},
 {'name': 'Kentucky',
  'children': [{'name': '1935', 'value': 2},
   {'name': '1936', 'value': 4},
   {'name': '1937', 'value': 3},
   {'name': '1938', 'value': 2},
   {'name': '1947', 'value': 4},
   {'name': '1949', 'value': 7},
   {'name': '1951', 'value': 3},
   {'name': '1953', 'value': 1},
   {'name': '1954', 'value': 1},
   {'name': '1956', 'value': 4},
   {'name': '1957', 'value': 1},
   {'name': '1958', 'value': 3},
   {'name': '1960', 'value': 2},
   {'name': '1962', 'value': 1},
   {'name': '1963', 'value': 7},
   {'name': '1964', 'value': 6},
   {'name': '1965', 'value': 5},
   {'name': '1969', 'value': 1},
   {'name': '1973', 'value': 3},
   {'name': '1979', 'value': 2},
   {'name': '1980', 'value': 1},
   {'name': '1983', 'value': 1},
   {'name': '1984', 'value': 1},
   {'name': '1987', 'value': 1},
   {'name': '1993', 'value': 1}]},
 {'name': 'Louisiana',
  'children': [{'name': '1952', 'value': 1},
   {'name': '1953', 'value': 1},
   {'name': '1955', 'value': 1},
   {'name': '1961', 'value': 1},
   {'name': '1984', 'value': 1},
   {'name': '1990', 'value': 1},
   {'name': '2001', 'value': 1}]},
 {'name': 'Massachusetts',
  'children': [{'name': '1912', 'value': 4},
   {'name': '1913', 'value': 1},
   {'name': '1916', 'value': 1},
   {'name': '1938', 'value': 2},
   {'name': '1962', 'value': 1},
   {'name': '1974', 'value': 1},
   {'name': '1982', 'value': 1},
   {'name': '1995', 'value': 1},
   {'name': '2005', 'value': 1}]},
 {'name': 'Maryland',
  'children': [{'name': '1947', 'value': 4},
   {'name': '1954', 'value': 1},
   {'name': '1956', 'value': 2},
   {'name': '1957', 'value': 2},
   {'name': '1964', 'value': 1},
   {'name': '1965', 'value': 1},
   {'name': '1966', 'value': 3},
   {'name': '1971', 'value': 1},
   {'name': '1973', 'value': 2},
   {'name': '1983', 'value': 1},
   {'name': '1988', 'value': 1}]},
 {'name': 'Maine',
  'children': [{'name': '1920', 'value': 4}, {'name': '2002', 'value': 2}]},
 {'name': 'Michigan',
  'children': [{'name': '1918', 'value': 8},
   {'name': '1919', 'value': 14},
   {'name': '1921', 'value': 34},
   {'name': '1942', 'value': 2},
   {'name': '1959', 'value': 4},
   {'name': '1960', 'value': 4},
   {'name': '1963', 'value': 5},
   {'name': '1968', 'value': 3},
   {'name': '1976', 'value': 1},
   {'name': '1977', 'value': 59},
   {'name': '1978', 'value': 1},
   {'name': '1980', 'value': 2},
   {'name': '1983', 'value': 2},
   {'name': '2005', 'value': 1},
   {'name': '2012', 'value': 2}]},
 {'name': 'Minnesota',
  'children': [{'name': '1937', 'value': 5},
   {'name': '1948', 'value': 1},
   {'name': '1950', 'value': 3},
   {'name': '1960', 'value': 4},
   {'name': '1963', 'value': 1},
   {'name': '1976', 'value': 1},
   {'name': '2009', 'value': 2}]},
 {'name': 'Missouri',
  'children': [{'name': '1922', 'value': 1},
   {'name': '1924', 'value': 1},
   {'name': '1977', 'value': 2}]},
 {'name': 'Mississippi',
  'children': [{'name': '1941', 'value': 4},
   {'name': '1957', 'value': 16},
   {'name': '1959', 'value': 1},
   {'name': '1973', 'value': 1},
   {'name': '1990', 'value': 1},
   {'name': '1994', 'value': 1},
   {'name': '2010', 'value': 1},
   {'name': '2016', 'value': 18}]},
 {'name': 'Montana',
  'children': [{'name': '1927', 'value': 4},
   {'name': '1932', 'value': 5},
   {'name': '1933', 'value': 7},
   {'name': '1934', 'value': 2},
   {'name': '1935', 'value': 2},
   {'name': '1937', 'value': 1},
   {'name': '1942', 'value': 1},
   {'name': '1947', 'value': 1},
   {'name': '1949', 'value': 1},
   {'name': '1951', 'value': 3},
   {'name': '1975', 'value': 1},
   {'name': '1976', 'value': 1},
   {'name': '1981', 'value': 1},
   {'name': '1998', 'value': 1},
   {'name': '2004', 'value': 1}]},
 {'name': 'North Carolina',
  'children': [{'name': '1952', 'value': 1},
   {'name': '1953', 'value': 1},
   {'name': '1958', 'value': 1},
   {'name': '1976', 'value': 1},
   {'name': '1980', 'value': 1},
   {'name': '1988', 'value': 1},
   {'name': '1992', 'value': 1},
   {'name': '1997', 'value': 1},
   {'name': '2005', 'value': 1},
   {'name': '2015', 'value': 1}]},
 {'name': 'North Dakota',
  'children': [{'name': '1930', 'value': 4},
   {'name': '1931', 'value': 13},
   {'name': '1935', 'value': 4},
   {'name': '1940', 'value': 4},
   {'name': '1941', 'value': 5},
   {'name': '1964', 'value': 1},
   {'name': '1982', 'value': 1},
   {'name': '1999', 'value': 1}]},
 {'name': 'Nebraska',
  'children': [{'name': '1919', 'value': 2},
   {'name': '1923', 'value': 6},
   {'name': '1931', 'value': 4},
   {'name': '1932', 'value': 3},
   {'name': '1935', 'value': 7},
   {'name': '1940', 'value': 1},
   {'name': '1941', 'value': 3},
   {'name': '1942', 'value': 1},
   {'name': '1944', 'value': 5},
   {'name': '1977', 'value': 1},
   {'name': '1979', 'value': 1}]},
 {'name': 'New Hampshire', 'children': []},
 {'name': 'New Jersey',
  'children': [{'name': '1918', 'value': 3},
   {'name': '1923', 'value': 2},
   {'name': '1935', 'value': 5},
   {'name': '1947', 'value': 1},
   {'name': '1948', 'value': 3},
   {'name': '1951', 'value': 12},
   {'name': '1957', 'value': 1},
   {'name': '1962', 'value': 2},
   {'name': '1965', 'value': 1},
   {'name': '1977', 'value': 3},
   {'name': '1989', 'value': 2},
   {'name': '1992', 'value': 3},
   {'name': '1998', 'value': 1},
   {'name': '2000', 'value': 6},
   {'name': '2004', 'value': 1},
   {'name': '2005', 'value': 2},
   {'name': '2007', 'value': 1},
   {'name': '2012', 'value': 1}]},
 {'name': 'New Mexico',
  'children': [{'name': '1931', 'value': 2},
   {'name': '1932', 'value': 6},
   {'name': '1934', 'value': 5},
   {'name': '1935', 'value': 4},
   {'name': '1937', 'value': 16},
   {'name': '1938', 'value': 3},
   {'name': '1939', 'value': 1},
   {'name': '1941', 'value': 2},
   {'name': '1942', 'value': 2},
   {'name': '1943', 'value': 5},
   {'name': '1944', 'value': 3},
   {'name': '1946', 'value': 7},
   {'name': '1947', 'value': 6},
   {'name': '1948', 'value': 9},
   {'name': '1950', 'value': 1},
   {'name': '1952', 'value': 1},
   {'name': '1955', 'value': 5},
   {'name': '1957', 'value': 1},
   {'name': '1962', 'value': 3},
   {'name': '1976', 'value': 1},
   {'name': '1978', 'value': 33},
   {'name': '1989', 'value': 2},
   {'name': '1996', 'value': 1},
   {'name': '1997', 'value': 1},
   {'name': '2007', 'value': 1},
   {'name': '2010', 'value': 1},
   {'name': '2015', 'value': 2}]},
 {'name': 'Nevada',
  'children': [{'name': '1944', 'value': 2},
   {'name': '1945', 'value': 1},
   {'name': '1954', 'value': 3},
   {'name': '1974', 'value': 3},
   {'name': '1985', 'value': 2},
   {'name': '1996', 'value': 1},
   {'name': '2006', 'value': 2}]},
 {'name': 'New York',
  'children': [{'name': '1914', 'value': 3},
   {'name': '1917', 'value': 7},
   {'name': '1918', 'value': 1},
   {'name': '1919', 'value': 7},
   {'name': '1920', 'value': 3},
   {'name': '1922', 'value': 2},
   {'name': '1923', 'value': 1},
   {'name': '1925', 'value': 1},
   {'name': '1928', 'value': 12},
   {'name': '1929', 'value': 1},
   {'name': '1931', 'value': 5},
   {'name': '1932', 'value': 3},
   {'name': '1933', 'value': 1},
   {'name': '1934', 'value': 3},
   {'name': '1939', 'value': 7},
   {'name': '1940', 'value': 1},
   {'name': '1943', 'value': 3},
   {'name': '1944', 'value': 3},
   {'name': '1945', 'value': 1},
   {'name': '1949', 'value': 4},
   {'name': '1956', 'value': 2},
   {'name': '1963', 'value': 2},
   {'name': '1966', 'value': 1},
   {'name': '1967', 'value': 2},
   {'name': '1971', 'value': 4},
   {'name': '1974', 'value': 3},
   {'name': '1975', 'value': 1},
   {'name': '1980', 'value': 2},
   {'name': '1982', 'value': 1},
   {'name': '1987', 'value': 2},
   {'name': '1989', 'value': 3},
   {'name': '1994', 'value': 1},
   {'name': '1999', 'value': 1},
   {'name': '2000', 'value': 1},
   {'name': '2014', 'value': 2}]},
 {'name': 'Ohio',
  'children': [{'name': '1919', 'value': 14},
   {'name': '1922', 'value': 10},
   {'name': '1933', 'value': 3},
   {'name': '1951', 'value': 1},
   {'name': '1953', 'value': 1},
   {'name': '1954', 'value': 1},
   {'name': '1957', 'value': 1},
   {'name': '1972', 'value': 4},
   {'name': '1974', 'value': 1},
   {'name': '1976', 'value': 2},
   {'name': '1981', 'value': 1},
   {'name': '1987', 'value': 1},
   {'name': '1994', 'value': 1},
   {'name': '2000', 'value': 4},
   {'name': '2004', 'value': 1},
   {'name': '2007', 'value': 3},
   {'name': '2008', 'value': 4},
   {'name': '2009', 'value': 1},
   {'name': '2011', 'value': 1},
   {'name': '2012', 'value': 1},
   {'name': '2014', 'value': 2},
   {'name': '2015', 'value': 27}]},
 {'name': 'Oklahoma',
  'children': [{'name': '1935', 'value': 2},
   {'name': '1949', 'value': 1},
   {'name': '1953', 'value': 1},
   {'name': '1956', 'value': 1},
   {'name': '1958', 'value': 1},
   {'name': '1972', 'value': 1},
   {'name': '1976', 'value': 7},
   {'name': '1984', 'value': 1},
   {'name': '1985', 'value': 1},
   {'name': '1994', 'value': 1},
   {'name': '2005', 'value': 1},
   {'name': '2011', 'value': 1},
   {'name': '2016', 'value': 2}]},

In [81]:
infant_children = []
for state in state_names:
    
    
    infant_data = session.query(bot_data.state_name,
                               bot_data.BotType,
                        bot_data.record_year,
                       func.sum(bot_data.record_count)).\
                        filter(bot_data.BotType == "Infant").\
                        filter(bot_data.state_name == state).\
                        group_by(bot_data.record_year).\
                        order_by(bot_data.state_name).all()
    
    children = []
    
    for i in infant_data:

        children.append({"name": i[2], "value": i[3]})
        
    
        
    one_state = {"name": state, "children": children}  
    infant_children.append(one_state)

In [82]:
wound_children = []
for state in state_names:
    
    
    wound_data = session.query(bot_data.state_name,
                               bot_data.BotType,
                        bot_data.record_year,
                       func.sum(bot_data.record_count)).\
                        filter(bot_data.BotType == "Wound").\
                        filter(bot_data.state_name == state).\
                        group_by(bot_data.record_year).\
                        order_by(bot_data.state_name).all()
    
    children = []
    
    for i in wound_data:

        children.append({"name": i[2], "value": i[3]})
        
    
        
    one_state = {"name": state, "children": children}  
    wound_children.append(one_state)

In [83]:
other_children = []
for state in state_names:
    
    
    other_data = session.query(bot_data.state_name,
                               bot_data.BotType,
                        bot_data.record_year,
                       func.sum(bot_data.record_count)).\
                        filter(bot_data.BotType == "Other").\
                        filter(bot_data.state_name == state).\
                        group_by(bot_data.record_year).\
                        order_by(bot_data.state_name).all()
    
    children = []
    
    for i in other_data:

        children.append({"name": i[2], "value": i[3]})
        
    
        
    one_state = {"name": state, "children": children}  
    other_children.append(one_state)

In [84]:
json= {"name": "botulism",
       "children":[
           {
           "name": "Foodborne",
            "children": food_children
           },
           {
            "name": "Infant",
            "children": infant_children
           },
           {"name": "Wound",
            "children": wound_children
           },
           {"name": "Other",
           "children": other_children}
       ]}

In [85]:
json

{'name': 'botulism',
 'children': [{'name': 'Foodborne',
   'children': [{'name': 'Alaska',
     'children': [{'name': '1947', 'value': 3},
      {'name': '1948', 'value': 4},
      {'name': '1950', 'value': 5},
      {'name': '1952', 'value': 1},
      {'name': '1956', 'value': 5},
      {'name': '1959', 'value': 10},
      {'name': '1960', 'value': 2},
      {'name': '1967', 'value': 1},
      {'name': '1968', 'value': 1},
      {'name': '1970', 'value': 1},
      {'name': '1971', 'value': 2},
      {'name': '1973', 'value': 12},
      {'name': '1974', 'value': 7},
      {'name': '1975', 'value': 3},
      {'name': '1976', 'value': 14},
      {'name': '1977', 'value': 11},
      {'name': '1979', 'value': 3},
      {'name': '1980', 'value': 2},
      {'name': '1981', 'value': 9},
      {'name': '1982', 'value': 3},
      {'name': '1983', 'value': 2},
      {'name': '1984', 'value': 6},
      {'name': '1985', 'value': 18},
      {'name': '1986', 'value': 8},
      {'name': '1987', 'value': 1},
      {'name': '1988', 'value': 32},
      {'name': '1989', 'value': 5},
      {'name': '1990', 'value': 8},
      {'name': '1991', 'value': 20},
      {'name': '1992', 'value': 8},
      {'name': '1993', 'value': 4},
      {'name': '1994', 'value': 11},
      {'name': '1995', 'value': 4},
      {'name': '1996', 'value': 10},
      {'name': '1997', 'value': 15},
      {'name': '1998', 'value': 9},
      {'name': '1999', 'value': 12},
      {'name': '2001', 'value': 9},
      {'name': '2002', 'value': 14},
      {'name': '2003', 'value': 2},
      {'name': '2004', 'value': 1},
      {'name': '2005', 'value': 8},
      {'name': '2006', 'value': 6},
      {'name': '2007', 'value': 10},
      {'name': '2008', 'value': 8},
      {'name': '2010', 'value': 5},
      {'name': '2011', 'value': 5},
      {'name': '2012', 'value': 3},
      {'name': '2013', 'value': 1},
      {'name': '2014', 'value': 7},
      {'name': '2015', 'value': 5},
      {'name': '2016', 'value': 2},
      {'name': '2017', 'value': 4}]},
    {'name': 'Alabama',
     'children': [{'name': '1928', 'value': 3},
      {'name': '1942', 'value': 1},
      {'name': '1962', 'value': 1},
      {'name': '1963', 'value': 3},
      {'name': '1964', 'value': 1},
      {'name': '1965', 'value': 2},
      {'name': '1974', 'value': 1}]},
    {'name': 'Arkansas',
     'children': [{'name': '1939', 'value': 2},
      {'name': '1961', 'value': 1},
      {'name': '1986', 'value': 3},
      {'name': '2000', 'value': 2},
      {'name': '2001', 'value': 1}]},
    {'name': 'Arizona',
     'children': [{'name': '1920', 'value': 5},
      {'name': '1945', 'value': 4},
      {'name': '1951', 'value': 1},
      {'name': '1955', 'value': 1},
      {'name': '1982', 'value': 3},
      {'name': '1983', 'value': 1},
      {'name': '1995', 'value': 1},
      {'name': '2001', 'value': 1},
      {'name': '2008', 'value': 1},
      {'name': '2011', 'value': 1},
      {'name': '2012', 'value': 12},
      {'name': '2014', 'value': 1}]},
    {'name': 'California',
     'children': [{'name': '1899', 'value': 1},
      {'name': '1902', 'value': 7},
      {'name': '1906', 'value': 3},
      {'name': '1910', 'value': 16},
      {'name': '1911', 'value': 1},
      {'name': '1912', 'value': 16},
      {'name': '1913', 'value': 16},
      {'name': '1914', 'value': 2},
      {'name': '1915', 'value': 8},
      {'name': '1916', 'value': 3},
      {'name': '1917', 'value': 10},
      {'name': '1918', 'value': 19},
      {'name': '1919', 'value': 14},
      {'name': '1920', 'value': 15},
      {'name': '1921', 'value': 3},
      {'name': '1922', 'value': 17},
      {'name': '1923', 'value': 10},
      {'name': '1924', 'value': 20},
      {'name': '1925', 'value': 8},
      {'name': '1926', 'value': 1},
      {'name': '1927', 'value': 4},
      {'name': '1928', 'value': 6},
      {'name': '1929', 'value': 10},
      {'name': '1930', 'value': 6},
      {'name': '1931', 'value': 12},
      {'name': '1932', 'value': 8},
      {'name': '1933', 'value': 10},
      {'name': '1934', 'value': 1},
      {'name': '1935', 'value': 21},
      {'name': '1936', 'value': 7},
      {'name': '1937', 'value': 13},
      {'name': '1938', 'value': 15},
      {'name': '1939', 'value': 14},
      {'name': '1940', 'value': 12},
      {'name': '1941', 'value': 17},
      {'name': '1942', 'value': 16},
      {'name': '1943', 'value': 11},
      {'name': '1944', 'value': 11},
      {'name': '1945', 'value': 22},
      {'name': '1946', 'value': 5},
      {'name': '1947', 'value': 6},
      {'name': '1948', 'value': 6},
      {'name': '1949', 'value': 2},
      {'name': '1950', 'value': 7},
      {'name': '1951', 'value': 12},
      {'name': '1952', 'value': 10},
      {'name': '1953', 'value': 2},
      {'name': '1954', 'value': 6},
      {'name': '1955', 'value': 3},
      {'name': '1956', 'value': 7},
      {'name': '1957', 'value': 5},
      {'name': '1958', 'value': 1},
      {'name': '1959', 'value': 3},
      {'name': '1962', 'value': 2},
      {'name': '1963', 'value': 10},
      {'name': '1964', 'value': 7},
      {'name': '1965', 'value': 2},
      {'name': '1966', 'value': 5},
      {'name': '1968', 'value': 4},
      {'name': '1969', 'value': 2},
      {'name': '1970', 'value': 2},
      {'name': '1971', 'value': 11},
      {'name': '1972', 'value': 18},
      {'name': '1973', 'value': 4},
      {'name': '1974', 'value': 3},
      {'name': '1975', 'value': 6},
      {'name': '1976', 'value': 8},
      {'name': '1977', 'value': 5},
      {'name': '1978', 'value': 3},
      {'name': '1979', 'value': 1},
      {'name': '1980', 'value': 4},
      {'name': '1981', 'value': 7},
      {'name': '1982', 'value': 11},
      {'name': '1983', 'value': 1},
      {'name': '1984', 'value': 7},
      {'name': '1985', 'value': 2},
      {'name': '1986', 'value': 6},
      {'name': '1987', 'value': 4},
      {'name': '1988', 'value': 1},
      {'name': '1989', 'value': 1},
      {'name': '1990', 'value': 3},
      {'name': '1991', 'value': 1},
      {'name': '1992', 'value': 2},
      {'name': '1993', 'value': 3},
      {'name': '1994', 'value': 6},
      {'name': '1995', 'value': 3},
      {'name': '1996', 'value': 3},
      {'name': '1997', 'value': 3},
      {'name': '1998', 'value': 6},
      {'name': '1999', 'value': 4},
      {'name': '2000', 'value': 3},
      {'name': '2001', 'value': 4},
      {'name': '2003', 'value': 2},
      {'name': '2004', 'value': 6},
      {'name': '2005', 'value': 3},
      {'name': '2006', 'value': 6},
      {'name': '2007', 'value': 1},
      {'name': '2008', 'value': 3},
      {'name': '2009', 'value': 4},
      {'name': '2010', 'value': 1},
      {'name': '2011', 'value': 1},
      {'name': '2012', 'value': 1},
      {'name': '2016', 'value': 3},
      {'name': '2017', 'value': 15}]},
    {'name': 'Colorado',
     'children': [{'name': '1912', 'value': 7},
      {'name': '1913', 'value': 5},
      {'name': '1915', 'value': 5},
      {'name': '1921', 'value': 5},
      {'name': '1924', 'value': 7},
      {'name': '1925', 'value': 5},
      {'name': '1927', 'value': 3},
      {'name': '1929', 'value': 6},
      {'name': '1930', 'value': 7},
      {'name': '1931', 'value': 4},
      {'name': '1932', 'value': 3},
      {'name': '1933', 'value': 1},
      {'name': '1934', 'value': 3},
      {'name': '1935', 'value': 8},
      {'name': '1936', 'value': 1},
      {'name': '1937', 'value': 3},
      {'name': '1938', 'value': 1},
      {'name': '1940', 'value': 4},
      {'name': '1941', 'value': 1},
      {'name': '1942', 'value': 11},
      {'name': '1944', 'value': 1},
      {'name': '1947', 'value': 2},
      {'name': '1948', 'value': 5},
      {'name': '1950', 'value': 3},
      {'name': '1951', 'value': 1},
      {'name': '1952', 'value': 1},
      {'name': '1953', 'value': 6},
      {'name': '1954', 'value': 2},
      {'name': '1955', 'value': 5},
      {'name': '1956', 'value': 6},
      {'name': '1957', 'value': 1},
      {'name': '1959', 'value': 2},
      {'name': '1962', 'value': 3},
      {'name': '1963', 'value': 2},
      {'name': '1967', 'value': 1},
      {'name': '1969', 'value': 7},
      {'name': '1970', 'value': 1},
      {'name': '1972', 'value': 1},
      {'name': '1977', 'value': 1},
      {'name': '1978', 'value': 9},
      {'name': '1980', 'value': 1},
      {'name': '1981', 'value': 1},
      {'name': '1982', 'value': 1},
      {'name': '1983', 'value': 2},
      {'name': '1988', 'value': 1},
      {'name': '1992', 'value': 2},
      {'name': '1995', 'value': 1},
      {'name': '1996', 'value': 1},
      {'name': '2003', 'value': 1},
      {'name': '2010', 'value': 1},
      {'name': '2014', 'value': 1}]},
    {'name': 'Connecticut',
     'children': [{'name': '1933', 'value': 5},
      {'name': '1942', 'value': 2},
      {'name': '1947', 'value': 2},
      {'name': '1976', 'value': 1},
      {'name': '1998', 'value': 1}]},
    {'name': '',
     'children': [{'name': '1946', 'value': 3},
      {'name': '1978', 'value': 3},
      {'name': '1992', 'value': 1},
      {'name': '2011', 'value': 1},
      {'name': '2012', 'value': 1}]},
    {'name': 'Delaware', 'children': [{'name': '2012', 'value': 1}]},
    {'name': 'Florida',
     'children': [{'name': '1916', 'value': 7},
      {'name': '1961', 'value': 1},
      {'name': '1975', 'value': 1},
      {'name': '1987', 'value': 4},
      {'name': '1988', 'value': 1},
      {'name': '1999', 'value': 4},
      {'name': '2006', 'value': 1}]},
    {'name': 'Georgia',
     'children': [{'name': '1943', 'value': 1},
      {'name': '1964', 'value': 1},
      {'name': '1974', 'value': 2},
      {'name': '1977', 'value': 1},
      {'name': '1978', 'value': 1},
      {'name': '1993', 'value': 4},
      {'name': '2006', 'value': 3},
      {'name': '2011', 'value': 1}]},
    {'name': 'Hawaii',
     'children': [{'name': '1981', 'value': 1},
      {'name': '1987', 'value': 1},
      {'name': '1988', 'value': 1},
      {'name': '1990', 'value': 4}]},
    {'name': 'Iowa',
     'children': [{'name': '1919', 'value': 5},
      {'name': '1974', 'value': 2},
      {'name': '1999', 'value': 1}]},
    {'name': 'Idaho',
     'children': [{'name': '1918', 'value': 4},
      {'name': '1932', 'value': 3},
      {'name': '1935', 'value': 1},
      {'name': '1939', 'value': 2},
      {'name': '1959', 'value': 6},
      {'name': '1961', 'value': 3},
      {'name': '1965', 'value': 3},
      {'name': '1969', 'value': 2},
      {'name': '1973', 'value': 1},
      {'name': '1974', 'value': 1},
      {'name': '1977', 'value': 1},
      {'name': '1981', 'value': 1},
      {'name': '1995', 'value': 6},
      {'name': '1996', 'value': 1}]},
    {'name': 'Illinois',
     'children': [{'name': '1915', 'value': 4},
      {'name': '1925', 'value': 2},
      {'name': '1929', 'value': 2},
      {'name': '1941', 'value': 1},
      {'name': '1944', 'value': 1},
      {'name': '1953', 'value': 4},
      {'name': '1956', 'value': 1},
      {'name': '1959', 'value': 1},
      {'name': '1967', 'value': 3},
      {'name': '1969', 'value': 1},
      {'name': '1970', 'value': 4},
      {'name': '1975', 'value': 1},
      {'name': '1983', 'value': 29},
      {'name': '1985', 'value': 1},
      {'name': '1991', 'value': 1},
      {'name': '1994', 'value': 1},
      {'name': '1997', 'value': 1},
      {'name': '2006', 'value': 1},
      {'name': '2014', 'value': 1},
      {'name': '2015', 'value': 2}]},
    {'name': 'Indiana',
     'children': [{'name': '1918', 'value': 7},
      {'name': '1921', 'value': 2},
      {'name': '1922', 'value': 9},
      {'name': '1954', 'value': 2},
      {'name': '1966', 'value': 2},
      {'name': '1969', 'value': 1},
      {'name': '1999', 'value': 1},
      {'name': '2007', 'value': 3},
      {'name': '2008', 'value': 1}]},
    {'name': 'Kansas',
     'children': [{'name': '1964', 'value': 7},
      {'name': '1970', 'value': 1},
      {'name': '1995', 'value': 1}]},
    {'name': 'Kentucky',
     'children': [{'name': '1935', 'value': 2},
      {'name': '1936', 'value': 4},
      {'name': '1937', 'value': 3},
      {'name': '1938', 'value': 2},
      {'name': '1947', 'value': 4},
      {'name': '1949', 'value': 7},
      {'name': '1951', 'value': 3},
      {'name': '1953', 'value': 1},
      {'name': '1954', 'value': 1},
      {'name': '1956', 'value': 4},
      {'name': '1957', 'value': 1},
      {'name': '1958', 'value': 3},
      {'name': '1960', 'value': 2},
      {'name': '1962', 'value': 1},
      {'name': '1963', 'value': 7},
      {'name': '1964', 'value': 6},
      {'name': '1965', 'value': 5},
      {'name': '1969', 'value': 1},
      {'name': '1973', 'value': 3},
      {'name': '1979', 'value': 2},
      {'name': '1980', 'value': 1},
      {'name': '1983', 'value': 1},
      {'name': '1984', 'value': 1},
      {'name': '1987', 'value': 1},
      {'name': '1993', 'value': 1}]},
    {'name': 'Louisiana',
     'children': [{'name': '1952', 'value': 1},
      {'name': '1953', 'value': 1},
      {'name': '1955', 'value': 1},
      {'name': '1961', 'value': 1},
      {'name': '1984', 'value': 1},
      {'name': '1990', 'value': 1},
      {'name': '2001', 'value': 1}]},
    {'name': 'Massachusetts',
     'children': [{'name': '1912', 'value': 4},
      {'name': '1913', 'value': 1},
      {'name': '1916', 'value': 1},
      {'name': '1938', 'value': 2},
      {'name': '1962', 'value': 1},
      {'name': '1974', 'value': 1},
      {'name': '1982', 'value': 1},
      {'name': '1995', 'value': 1},
      {'name': '2005', 'value': 1}]},
    {'name': 'Maryland',
     'children': [{'name': '1947', 'value': 4},
      {'name': '1954', 'value': 1},
      {'name': '1956', 'value': 2},
      {'name': '1957', 'value': 2},
      {'name': '1964', 'value': 1},
      {'name': '1965', 'value': 1},
      {'name': '1966', 'value': 3},
      {'name': '1971', 'value': 1},
      {'name': '1973', 'value': 2},
      {'name': '1983', 'value': 1},
      {'name': '1988', 'value': 1}]},
    {'name': 'Maine',
     'children': [{'name': '1920', 'value': 4}, {'name': '2002', 'value': 2}]},
    {'name': 'Michigan',
     'children': [{'name': '1918', 'value': 8},
      {'name': '1919', 'value': 14},
      {'name': '1921', 'value': 34},
      {'name': '1942', 'value': 2},
      {'name': '1959', 'value': 4},
      {'name': '1960', 'value': 4},
      {'name': '1963', 'value': 5},
      {'name': '1968', 'value': 3},
      {'name': '1976', 'value': 1},
      {'name': '1977', 'value': 59},
      {'name': '1978', 'value': 1},
      {'name': '1980', 'value': 2},
      {'name': '1983', 'value': 2},
      {'name': '2005', 'value': 1},
      {'name': '2012', 'value': 2}]},
    {'name': 'Minnesota',
     'children': [{'name': '1937', 'value': 5},
      {'name': '1948', 'value': 1},
      {'name': '1950', 'value': 3},
      {'name': '1960', 'value': 4},
      {'name': '1963', 'value': 1},
      {'name': '1976', 'value': 1},
      {'name': '2009', 'value': 2}]},
    {'name': 'Missouri',
     'children': [{'name': '1922', 'value': 1},
      {'name': '1924', 'value': 1},
      {'name': '1977', 'value': 2}]},
    {'name': 'Mississippi',
     'children': [{'name': '1941', 'value': 4},
      {'name': '1957', 'value': 16},
      {'name': '1959', 'value': 1},
      {'name': '1973', 'value': 1},
      {'name': '1990', 'value': 1},
      {'name': '1994', 'value': 1},
      {'name': '2010', 'value': 1},
      {'name': '2016', 'value': 18}]},
    {'name': 'Montana',
     'children': [{'name': '1927', 'value': 4},
      {'name': '1932', 'value': 5},
      {'name': '1933', 'value': 7},
      {'name': '1934', 'value': 2},
      {'name': '1935', 'value': 2},
      {'name': '1937', 'value': 1},
      {'name': '1942', 'value': 1},
      {'name': '1947', 'value': 1},
      {'name': '1949', 'value': 1},
      {'name': '1951', 'value': 3},
      {'name': '1975', 'value': 1},
      {'name': '1976', 'value': 1},
      {'name': '1981', 'value': 1},
      {'name': '1998', 'value': 1},
      {'name': '2004', 'value': 1}]},
    {'name': 'North Carolina',
     'children': [{'name': '1952', 'value': 1},
      {'name': '1953', 'value': 1},
      {'name': '1958', 'value': 1},
      {'name': '1976', 'value': 1},
      {'name': '1980', 'value': 1},
      {'name': '1988', 'value': 1},
      {'name': '1992', 'value': 1},
      {'name': '1997', 'value': 1},
      {'name': '2005', 'value': 1},
      {'name': '2015', 'value': 1}]},
    {'name': 'North Dakota',
     'children': [{'name': '1930', 'value': 4},
      {'name': '1931', 'value': 13},
      {'name': '1935', 'value': 4},
      {'name': '1940', 'value': 4},
      {'name': '1941', 'value': 5},
      {'name': '1964', 'value': 1},
      {'name': '1982', 'value': 1},
      {'name': '1999', 'value': 1}]},
    {'name': 'Nebraska',
     'children': [{'name': '1919', 'value': 2},
      {'name': '1923', 'value': 6},
      {'name': '1931', 'value': 4},
      {'name': '1932', 'value': 3},
      {'name': '1935', 'value': 7},
      {'name': '1940', 'value': 1},
      {'name': '1941', 'value': 3},
      {'name': '1942', 'value': 1},
      {'name': '1944', 'value': 5},
      {'name': '1977', 'value': 1},
      {'name': '1979', 'value': 1}]},
    {'name': 'New Hampshire', 'children': []},
    {'name': 'New Jersey',
     'children': [{'name': '1918', 'value': 3},
      {'name': '1923', 'value': 2},
      {'name': '1935', 'value': 5},
      {'name': '1947', 'value': 1},
      {'name': '1948', 'value': 3},
      {'name': '1951', 'value': 12},
      {'name': '1957', 'value': 1},
      {'name': '1962', 'value': 2},
      {'name': '1965', 'value': 1},
      {'name': '1977', 'value': 3},
      {'name': '1989', 'value': 2},
      {'name': '1992', 'value': 3},
      {'name': '1998', 'value': 1},
      {'name': '2000', 'value': 6},
      {'name': '2004', 'value': 1},
      {'name': '2005', 'value': 2},
      {'name': '2007', 'value': 1},
      {'name': '2012', 'value': 1}]},
    {'name': 'New Mexico',
     'children': [{'name': '1931', 'value': 2},
      {'name': '1932', 'value': 6},
      {'name': '1934', 'value': 5},
      {'name': '1935', 'value': 4},
      {'name': '1937', 'value': 16},
      {'name': '1938', 'value': 3},
      {'name': '1939', 'value': 1},
      {'name': '1941', 'value': 2},
      {'name': '1942', 'value': 2},
      {'name': '1943', 'value': 5},
      {'name': '1944', 'value': 3},
      {'name': '1946', 'value': 7},
      {'name': '1947', 'value': 6},
      {'name': '1948', 'value': 9},
      {'name': '1950', 'value': 1},
      {'name': '1952', 'value': 1},
      {'name': '1955', 'value': 5},
      {'name': '1957', 'value': 1},
      {'name': '1962', 'value': 3},
      {'name': '1976', 'value': 1},
      {'name': '1978', 'value': 33},
      {'name': '1989', 'value': 2},
      {'name': '1996', 'value': 1},
      {'name': '1997', 'value': 1},
      {'name': '2007', 'value': 1},
      {'name': '2010', 'value': 1},
      {'name': '2015', 'value': 2}]},
    {'name': 'Nevada',
     'children': [{'name': '1944', 'value': 2},
      {'name': '1945', 'value': 1},
      {'name': '1954', 'value': 3},
      {'name': '1974', 'value': 3},
      {'name': '1985', 'value': 2},
      {'name': '1996', 'value': 1},
      {'name': '2006', 'value': 2}]},
    {'name': 'New York',
     'children': [{'name': '1914', 'value': 3},
      {'name': '1917', 'value': 7},
      {'name': '1918', 'value': 1},
      {'name': '1919', 'value': 7},
      {'name': '1920', 'value': 3},
      {'name': '1922', 'value': 2},
      {'name': '1923', 'value': 1},
      {'name': '1925', 'value': 1},
      {'name': '1928', 'value': 12},
      {'name': '1929', 'value': 1},
      {'name': '1931', 'value': 5},
      {'name': '1932', 'value': 3},
      {'name': '1933', 'value': 1},
      {'name': '1934', 'value': 3},
      {'name': '1939', 'value': 7},
      {'name': '1940', 'value': 1},
      {'name': '1943', 'value': 3},
      {'name': '1944', 'value': 3},
      {'name': '1945', 'value': 1},
      {'name': '1949', 'value': 4},